// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // API keys are injected at build time to avoid committing sensitive literals.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:872045622743:web:0a7f7b8c7473433bb44792',
    messagingSenderId: '872045622743',
    projectId: 'fitnesstracker-b65e4',
    authDomain: 'fitnesstracker-b65e4.firebaseapp.com',
    storageBucket: 'fitnesstracker-b65e4.firebasestorage.app',
    measurementId: 'G-PYBMZ2P92R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:872045622743:android:eaf9f760456ceaf7b44792',
    messagingSenderId: '872045622743',
    projectId: 'fitnesstracker-b65e4',
    storageBucket: 'fitnesstracker-b65e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:872045622743:ios:35349e528892ac9eb44792',
    messagingSenderId: '872045622743',
    projectId: 'fitnesstracker-b65e4',
    storageBucket: 'fitnesstracker-b65e4.firebasestorage.app',
    androidClientId: '872045622743-04e0pl1drsv9b40okgn7u1cfvj7v2tep.apps.googleusercontent.com',
    iosClientId: '872045622743-m63rjejvv5f2ni6vork8p5du01dnee3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY'),
    appId: '1:872045622743:ios:26346ddc4074de4eb44792',
    messagingSenderId: '872045622743',
    projectId: 'fitnesstracker-b65e4',
    storageBucket: 'fitnesstracker-b65e4.firebasestorage.app',
    androidClientId: '872045622743-04e0pl1drsv9b40okgn7u1cfvj7v2tep.apps.googleusercontent.com',
    iosClientId: '872045622743-4eh9d8aa1k257b9jf7fjejgvdc0mauje.apps.googleusercontent.com',
    iosBundleId: 'com.auribises.eventhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:872045622743:web:b43363d41e82ccd5b44792',
    messagingSenderId: '872045622743',
    projectId: 'fitnesstracker-b65e4',
    authDomain: 'fitnesstracker-b65e4.firebaseapp.com',
    storageBucket: 'fitnesstracker-b65e4.firebasestorage.app',
    measurementId: 'G-475WTHK6T1',
  );
}
